config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  

  resources :phones
  resources :addresses
  resources :contacts
  resources :hospitals
  resources :kinds #cria 8 rotas de forma automatica (rails/info)
  

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  belongs_to :contact
  has_many :address
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]

  # GET /hospitals
  # GET /hospitals.json
  def index
    @hospitals = Hospital.all
  end

  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully created.' }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1
  # PATCH/PUT /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital.destroy
    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: 'Hospital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_params
      params.require(:hospital).permit(:name, :street, :city, :state, :contact_id)
    end
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/_form.html.erb
<%= form_for(@hospital) do |f| %>
  <% if @hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
      <% @hospital.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :contact_id %><br>
    <%= f.text_field :contact_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hospitals/edit.html.erb
<h1>Editing Hospital</h1>

<%= render 'form' %>

<%= link_to 'Show', @hospital %> |
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hospitals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= hospital.name %></td>
        <td><%= hospital.street %></td>
        <td><%= hospital.city %></td>
        <td><%= hospital.state %></td>
        <td><%= hospital.contact %></td>
        <td><%= link_to 'Show', hospital %></td>
        <td><%= link_to 'Edit', edit_hospital_path(hospital) %></td>
        <td><%= link_to 'Destroy', hospital, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hospital', new_hospital_path %>

app/views/hospitals/new.html.erb
<h1>New Hospital</h1>

<%= render 'form' %>

<%= link_to 'Back', hospitals_path %>

app/views/hospitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hospital.name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @hospital.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @hospital.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @hospital.state %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @hospital.contact %>
</p>

<%= link_to 'Edit', edit_hospital_path(@hospital) %> |
<%= link_to 'Back', hospitals_path %>